### ISSUE TITLE
Feature-Request: Collages in App

### ISSUE THREAD

**Issue by capital-G** [stuxo/REDAndroid#14]
Currently there is no support for Collages in the App - would it be possible to change this?

**Comment by stuxo** [comment]
Yep, there is an API for it I believe. Just open up a pull request, I'm happy to review it.

**Comment by capital-G** [comment]
Okay, I started some coding today - I implemented the Data Model and created a `CollageSearchActivity` and a `CollageActivity`, still have to do some UI wiring to do.

First time writing Android - I am impressed how much stuff you have to care about.

**Comment by capital-G** [comment]
Continued some coding today - can you give some feedback?

https://github.com/capital-G/REDAndroid/tree/feature-collages

![Screenshot_1576447641](https://user-images.githubusercontent.com/8267062/70870437-af4e0180-1f93-11ea-8231-01651c37c553.png)

![Screenshot_1576447672](https://user-images.githubusercontent.com/8267062/70870439-b37a1f00-1f93-11ea-9de5-eaa0ae516cd2.png)

![Screenshot_1576447695](https://user-images.githubusercontent.com/8267062/70870443-b83ed300-1f93-11ea-91be-ab783ba16432.png)

The UI is still clunky on some spots

* [ ] Icon and order in Drawer should be more senseful
* [ ] Height of Collage Search is messed up
* [ ] Year/Tags on Detail View are wrong (not binded yet)
* [ ] What happens if a release has no artist?
* [ ] Collage Comments are not displayed
* [ ] Collage Description is not displayed

Nice to have IMO:
* [ ] Bookmark collages

**Comment by capital-G** [comment]
I decided to leave out

* description
* comments
* bookmarking

for now as I struggle with those features and I think its better to have at least minimum collage functionality than none
