### ISSUE TITLE
Version information blank

### ISSUE THREAD

**Issue by psylk** [stuxo/REDAndroid#5]
In settings, under REDAndroid Version, there's just the string '[RED]Android' with no version number.

![vli67e2](https://user-images.githubusercontent.com/23621154/28446102-20a36566-6dfb-11e7-8202-cd6bf29adee2.jpg)

**Comment by psylk** [comment]
Screenshot here: https://i.cubeupload.com/vlI67E.jpg

**Comment by stuxo** [comment]
Fixed in pull request https://github.com/stuxo/REDAndroid/pull/6
Closing as resolved.
